type dev\ref\add_to_class.cfg >> ..\..\cfg\scout.cfg
type dev\ref\add_to_class.cfg >> ..\..\cfg\soldier.cfg
type dev\ref\add_to_class.cfg >> ..\..\cfg\pyro.cfg
type dev\ref\add_to_class.cfg >> ..\..\cfg\demoman.cfg
type dev\ref\add_to_class.cfg >> ..\..\cfg\heavyweapons.cfg
type dev\ref\add_to_class.cfg >> ..\..\cfg\engineer.cfg
type dev\ref\add_to_class.cfg >> ..\..\cfg\medic.cfg
type dev\ref\add_to_class.cfg >> ..\..\cfg\sniper.cfg
type dev\ref\add_to_class.cfg >> ..\..\cfg\spy.cfg